name: Deploy to ArgoCD

on:
  pull_request:
    types:
      - opened

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "PR_NAMESPACE=${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Replace Values in manifests
        run: |
          sed -i '' "s/{REPLACE_REPO_NAME}/${{ github.event.repository.name }}/g" applicationset.yaml
          sed -i '' "s/{REPLACE_REPO_NAME}-pr-{{number}}/$PR_NAMESPACE/g" applicationset.yaml

      - name: Commit and Push Changes (Optional)
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --global user.name "rijuchatterjee"
          git config --global user.email "chatterjeeriju56@gmail.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git add applicationset.yaml
          git commit -m "Update manifests dynamically for $PR_NAMESPACE" || echo "No changes to commit"
          git push origin HEAD:$GITHUB_REF

      - name: Create Namespace in Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl create namespace $PR_NAMESPACE || echo "Namespace already exists"

      - name: Apply Manifests to ArgoCD
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f applicationset.yaml